### ISSUE TITLE
Equation in the tutorial does not get rendered

### ISSUE THREAD

**Issue by gabkdlly** [pymc-devs/pymc2#158]
At three points in the tutorial, there is a reference to an equation labeled `disaster_model`.  But reading the tutorial in the web-browser, these equations are simply rendered as `(?)`.

**Comment by fonnesbeck** [comment]
Are you talking about the tutorial [here](https://pymc-devs.github.io/pymc/tutorial.html?highlight=disaster_model)? They render fine at my end. Perhaps check your JavaScript settings on your browser (or try another browser)? They use MathJax, which is a JS library. 

If you are talking about something else, please post the link so I can try to reproduce the issue here.

**Comment by gabkdlly** [comment]
Yes, [https://pymc-devs.github.io/pymc/tutorial.html#equation-disaster_model](here).  That is, in section 3.2 for example, in fourth paragraph of that section, where it starts with:  "We can represent model (?) in a file called disaster_model.py ..."  I have tested Chromium and Firefox web browsers, both on Ubuntu GNU/Linux 17.04, and both show this behavior.
