### ISSUE TITLE
Inference with Theano shared variable having missing data

### ISSUE THREAD

**Issue by FlorianWilhelm** [pymc-devs/pymc2#181]
According to the documentation, pymc3 creates automatically random variables which model missing values if numpy arrays containing NaNs or a masked arrays are provided as observations. This works fine for me. Also according to the documentation if I want to sample from my posterior in order to get predictions, Theano shared variables should be used already during the inference. Now passing a Theano shared variable (constructed with a numpy array having missing values) as observations does not automatically create a `_missing` random variable as before. It would be nice to mention that in the documentation and to give an example as well as helper functions to manually construct these random variables to encode masked values.

**Comment by fonnesbeck** [comment]
You've made a common error, which is to post a PyMC3 question in the PyMC issue tracker. Actually, since this is not a bug report per se, the best place to post it is in our [Discourse forum](discourse.pymc.io). I will close this, but also address your question:

You don't need to use shared variables for predictions, necessarily. You can use `sample_ppc` (or `sample_posterior_predictive` if you are running the master branch). You can also create prediction nodes in your model, if you prefer.

**Comment by FlorianWilhelm** [comment]
@fonnesbeck Thanks for your help. I was just following the [Predicting on hold-out data section](https://docs.pymc.io/notebooks/api_quickstart.html?highlight=prediction#4.1-Predicting-on-hold-out-data) but I'll check out the forum now. Thanks again.
