### ISSUE TITLE
Exponential interface is misleading/confusing

### ISSUE THREAD

**Issue by jamestwebber** [pymc-devs/pymc2#31]
You use the parameter beta for the exponential distribution but you treat it like _lambda_, the reciprocal of beta (in terms of the common description of this distribution, see [Wikipedia](http://en.wikipedia.org/wiki/Exponential_distribution), [Wolfram](http://mathworld.wolfram.com/ExponentialDistribution.html), etc). Beta should be the mean but when I build an exponential and generate random values they have mean 1/Beta.

This means that when you want a really large exponential you get a really small one and vice versa. This is really confusing! It would be good to either rename the parameter or change the behavior.

I can submit a PR if needed, but I not very familiar with the structure of the distributions module and wasn't sure where to start.

**Comment by fonnesbeck** [comment]
Parameterizing the exponential (and gamma) using the scale parameter (your suggestion) or the rate parameter (current implementation) are equally cmmon in the literature (though perhaps not within a particular literature), so it is never obvious which to use. PyMC's choice was made based on its prevalence with other probabilistic programming langauges. BUGS, JAGS and Stan all use the rate parameter, so we should probably stick with it. This is the same reason we use a precision parameter rather than variance in the Normal distribution, though there is some momentum for changing that.

I would be open to having an optional `scale=` keyword parameter, if you feel like submitting a PR, but for now we should keep the defaullt as rate.

**Comment by jamestwebber** [comment]
I must have been unclear. My issue isn't with the choice of scale vs rate. It's that the parameter name (`beta`) is usually referring to the scale, but PyMC uses it for the rate (usually called `lambda`). Typically, EV = Beta = 1 / Lambda. Here, EV = 1 / Beta.

The naming switcheroo led me to some confusing bugs until I figured out the situation. Example below:

``` python
import pymc as pm
exp = pm.Exponential('exp', beta=10.0, size=10000)
exp.random().mean() # should be 10.0
Out[3]: 0.10080710788225443
exp = pm.Exponential('exp', beta=100.0, size=10000)
exp.random().mean() # should be 100.0
Out[5]: 0.0097913529794816448
```

When I wrote the issue I was unaware that pymc3 existed--in pymc3 the parameter is called `lam` instead. Changing the name of this parameter would break compatibility so it seems like a tough issue at this point. A warning in the documentation might be worthwhile though.

**Comment by fonnesbeck** [comment]
I see now. Yes, you are right -- we probably should have called it `lam`
(lambda is not a good name in Python). Since this is the first time it has
come up, I will not worry too much about it, but glad we got things
straightened out in PyMC 3.
