### ISSUE TITLE
The convergence of the Hidden Markov Model

### ISSUE THREAD

**Issue by sshegheva** [pymc-devs/pymc2#64]
Hi, I am having an issue with my hidden markov model implementation in PyMC. 

By collecting ideas from various sources: https://gist.github.com/fonnesbeck/342989, stackoverflow questions, Bayesian Method for Hackers book and PyMC documentation, I have implemented following model:

https://gist.github.com/sshegheva/f334dae604dcc1505fba.

At first, I was debugging the convergence through MCMC by letting the model run for 10000 iterations and half of the points burned. However, the model seemed to have high autocorrelation. 

Attempting to call MAP function with subsequent fit causes the model to hang. 

```
### THIS PART TAKES A LONG TIME
map_ = pymc.MAP(model)

### THIS PART NEVER COMPLETES
map_.fit()

mcmc = pymc.MCMC(model)
```

What are other things I should try to debug the convergence? Is there something fundamentally wrong with my model or my assumptions on the speed of MAP?

The model has 3 hidden states and 2 emission states. Total number of observations is 1441.

P.S. I am not able to attach the simulated_observations.csv file due to permission issues. Let me know if you can access the file from here if needed https://github.gatech.edu/sshegheva3/aslept/blob/master/notebooks/simulated_observations.csv

**Comment by fonnesbeck** [comment]
This is not really a bug report, so I'm going to close the issue. The best place to look for modeling advice for PyMC is on [Stack Overflow](http://stackoverflow.com/questions/tagged/pymc) using the`pymc` tag. There could be a variety of reasons for the model not converging or running slowly, having to do with the data or the model structure. I noted a couple of things to keep in mind:
1. you don't have to create `Container` objects explicitly -- PyMC will automatically create them when it sees arrays or lists with PyMC objects in them.
2. models with a lot of Python loops will tend to be slow
3. you might want to pass `locals()` to `MCMC` rather than a list of variables, just to ensure you got everything. I noticed that `x_0` and `y_0` are not passed when they should be.

**Comment by sshegheva** [comment]
@fonnesbeck thank you! I will make adjustments and will repost the question on stack overflow.
